MKDIR = mkdir -p
CXX = g++
CXXFLAGS = -std=c++14 $(INCLUDE)
INCLUDE = -Iinclude/
LDLIBS = -lpng -lX11 -lGL -lGLEW

BIN_DIR = bin/
TEST_DIR = tests/
TEST_BIN_DIR = bin/tests/

TESTS = $(wildcard $(TEST_DIR)*/*.cpp)
TEST_OUTPUTS =  $(TESTS:
#TEST_OUTPUTS = $(TESTS:.cpp=)

$(BIN_DIR):
	 $(MKDIR) $(BIN_DIR)

$(TEST_BIN_DIR): $(BIN_DIR)
	$(MKDIR) $(TEST_BIN_DIR)

#$(TEST_DIR)/%/% : test/%.cpp $(PROJS_BIN_DIR)
#	$(CXX) $(CXXFLAGS) $(INCLUDE) $(LDLIBS) -o $(BIN_DIR)$@ $<

all_tests : $(TEST_OUTPUTS)
	$(info $$TEST_OUTPUTS is [${TEST_OUTPUTS}])

all: all_tests run_all

run_all:
	@for dir in $(TEST_BIN_DIR)*; do run-parts $$dir; done

clean:
	rm -drf $(BIN_DIR) $(TEST_BIN_DIR)
